set guioptions-=T " hide toolbar

Bundle 'Indent-Guides'
let g:indent_guides_enable_on_vim_startup = 1 
" Disable the scrollbars (NERDTree)
set guioptions-=r  "remove right-hand scroll bar
set guioptions-=l

colorscheme pyte
set guifont=Consolas\ 11
set anti
set lines=999 columns=84
set guioptions=egmrt
set novisualbell

